Repository SOEN6431Winter2025/OpenTracksW25, pull requests merged in 2025-04, with the labels that each got.

#121 Software Vulnerabilities Detection and Fix (Group #5)
  build.gradle
  src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
  src/main/java/de/dennisguse/opentracks/data/SelectionData.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerUtils.java
  src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
Labels: Group 5, Remove Software vulnerability

#123 Group7 - Case study3- Software Vulnerabilities
  src/main/AndroidManifest.xml
  src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
  src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
  src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
  src/main/java/de/dennisguse/opentracks/publicapi/CreateMarkerActivity.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
  src/main/java/de/dennisguse/opentracks/util/PermissionRequester.java
Labels: Group 7, Remove Software vulnerability

#125 Group6: Software Vulnerabilities
  .vscode/settings.json
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
  src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java
  src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
  src/main/java/de/dennisguse/opentracks/data/Id.java
  src/main/java/de/dennisguse/opentracks/data/SelectionData.java
  src/main/java/de/dennisguse/opentracks/data/models/Marker.java
  src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
  src/main/java/de/dennisguse/opentracks/data/tables/MarkerColumns.java
  src/main/java/de/dennisguse/opentracks/data/tables/TrackPointsColumns.java
  src/main/java/de/dennisguse/opentracks/data/tables/TracksColumns.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
  src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
  src/main/java/de/dennisguse/opentracks/publicapi/CreateMarkerActivity.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerUtils.java
  src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
  src/main/java/de/dennisguse/opentracks/util/PermissionRequester.java
Labels: Group 6, Remove Software vulnerability
